# Generated by Django 2.0.2 on 2018-03-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDisplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='zhihu_anwsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=100, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('answer_count', models.IntegerField(null=True)),
                ('zhihu_url', models.CharField(max_length=100, null=True)),
                ('public_answer_count', models.IntegerField(null=True)),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('user_name', models.TextField(max_length=100, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('avatar_url', models.CharField(max_length=100, null=True)),
                ('question_price', models.IntegerField(null=True)),
                ('follower_count', models.IntegerField(null=True)),
            ],
        ),
    ]
