# Generated by Django 2.0.2 on 2018-03-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDisplay', '0002_zhihu_anwsers'),
    ]

    operations = [
        migrations.CreateModel(
            name='headline_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id', models.IntegerField(null=True)),
                ('images_url', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='headline_title_and_url',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
