# Generated by Django 2.0.2 on 2018-03-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDisplay', '0004_wangyi_news_wangyi_news_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sina_news',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100, null=True)),
                ('tag', models.TextField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('article', models.TextField(max_length=3000, null=True)),
            ],
        ),
    ]
