# Generated by Django 2.0.2 on 2018-03-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDisplay', '0005_sina_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sina_weibo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nike', models.CharField(max_length=40, null=True)),
                ('image_url', models.CharField(max_length=500, null=True)),
                ('home_page', models.CharField(max_length=500, null=True)),
                ('follow_count', models.IntegerField(null=True)),
                ('followers_count', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=2, null=True)),
                ('urank', models.IntegerField(null=True)),
                ('description', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sina_weibo_content',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=1000, null=True)),
                ('liked_num', models.IntegerField(null=True)),
                ('comment_num', models.IntegerField(null=True)),
                ('shared_num', models.IntegerField(null=True)),
                ('userid', models.CharField(max_length=20, null=True)),
                ('source', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
