# Generated by Django 2.0.2 on 2018-03-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDisplay', '0007_taobao_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='baidu_picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imgurl', models.CharField(max_length=100, null=True)),
                ('imgname', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
