# Generated by Django 2.0.2 on 2018-03-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataDisplay', '0011_auto_20180328_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline_images',
            name='abstracts',
        ),
        migrations.RemoveField(
            model_name='headline_images',
            name='images_url',
        ),
    ]
