# Generated by Django 2.0.2 on 2018-03-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDisplay', '0014_auto_20180328_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline_images',
            name='abstracts',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='headline_images',
            name='images_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
