# Generated by Django 2.0.2 on 2018-03-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataDisplay', '0015_auto_20180328_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wangyi_news_images',
            name='imgurl',
        ),
        migrations.RemoveField(
            model_name='wangyi_news_images',
            name='note',
        ),
    ]
