# Generated by Django 2.0.2 on 2018-04-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDisplay', '0017_auto_20180328_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='dianyan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=100, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('answer_count', models.IntegerField(null=True)),
                ('zhihu_url', models.CharField(max_length=100, null=True)),
                ('public_answer_count', models.IntegerField(null=True)),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('user_name', models.TextField(max_length=100, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('avatar_url', models.CharField(max_length=100, null=True)),
                ('question_price', models.IntegerField(null=True)),
                ('follower_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='meishi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=100, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('answer_count', models.IntegerField(null=True)),
                ('zhihu_url', models.CharField(max_length=100, null=True)),
                ('public_answer_count', models.IntegerField(null=True)),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('user_name', models.TextField(max_length=100, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('avatar_url', models.CharField(max_length=100, null=True)),
                ('question_price', models.IntegerField(null=True)),
                ('follower_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xinlixue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=100, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('answer_count', models.IntegerField(null=True)),
                ('zhihu_url', models.CharField(max_length=100, null=True)),
                ('public_answer_count', models.IntegerField(null=True)),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('user_name', models.TextField(max_length=100, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('avatar_url', models.CharField(max_length=100, null=True)),
                ('question_price', models.IntegerField(null=True)),
                ('follower_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='yinyue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=100, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('answer_count', models.IntegerField(null=True)),
                ('zhihu_url', models.CharField(max_length=100, null=True)),
                ('public_answer_count', models.IntegerField(null=True)),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('user_name', models.TextField(max_length=100, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('avatar_url', models.CharField(max_length=100, null=True)),
                ('question_price', models.IntegerField(null=True)),
                ('follower_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='youxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=100, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('answer_count', models.IntegerField(null=True)),
                ('zhihu_url', models.CharField(max_length=100, null=True)),
                ('public_answer_count', models.IntegerField(null=True)),
                ('user_id', models.CharField(max_length=100, null=True)),
                ('user_name', models.TextField(max_length=100, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('avatar_url', models.CharField(max_length=100, null=True)),
                ('question_price', models.IntegerField(null=True)),
                ('follower_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='wangyi_news',
            name='overview',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='wangyi_news',
            name='title',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
